// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDzBLEdqYS9r7Vskjo4lI74YAR7WxLPbY',
    appId: '1:591406178238:web:d68a2bf6f99ca7661da3ef',
    messagingSenderId: '591406178238',
    projectId: 'delivery-app-73305',
    authDomain: 'delivery-app-73305.firebaseapp.com',
    databaseURL: 'https://delivery-app-73305-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-app-73305.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3NhPTcO6zM0Z10SUMLLk-YP7TtEgHZJI',
    appId: '1:591406178238:ios:52436f95b921e40d1da3ef',
    messagingSenderId: '591406178238',
    projectId: 'delivery-app-73305',
    databaseURL: 'https://delivery-app-73305-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-app-73305.firebasestorage.app',
    androidClientId: '591406178238-g90dvs1js5pr9r4d9d8qf66nr52u6igs.apps.googleusercontent.com',
    iosClientId: '591406178238-4tjgk5suqfkm2o3qing0iak072ucqrtd.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3NhPTcO6zM0Z10SUMLLk-YP7TtEgHZJI',
    appId: '1:591406178238:ios:52436f95b921e40d1da3ef',
    messagingSenderId: '591406178238',
    projectId: 'delivery-app-73305',
    databaseURL: 'https://delivery-app-73305-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-app-73305.firebasestorage.app',
    androidClientId: '591406178238-g90dvs1js5pr9r4d9d8qf66nr52u6igs.apps.googleusercontent.com',
    iosClientId: '591406178238-4tjgk5suqfkm2o3qing0iak072ucqrtd.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDzBLEdqYS9r7Vskjo4lI74YAR7WxLPbY',
    appId: '1:591406178238:web:64b0c3911b8866b91da3ef',
    messagingSenderId: '591406178238',
    projectId: 'delivery-app-73305',
    authDomain: 'delivery-app-73305.firebaseapp.com',
    databaseURL: 'https://delivery-app-73305-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-app-73305.firebasestorage.app',
  );
}
